FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build
RUN ./node_modules/.bin/tsc typeorm.config.ts --outDir dist --module commonjs --target es2019 --skipLibCheck --esModuleInterop

FROM node:20-alpine AS production
WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["sh", "-c", "npm run migration:run:prod && npm run start:prod"]