export const TIME_LIMIT_CHECK_CONSTANTS = {
  TIME: {
    MILLISECONDS_PER_MINUTE: 60000,
    DAY_START_HOUR: 0,
    DAY_START_MINUTE: 0,
    DAY_START_SECOND: 0,
    DAY_START_MILLISECOND: 0,
  },
  LIMITS: {
    MIN_LIMIT: 0,
    INITIAL_TOTAL_MINUTES: 0,
  },
} as const;
