name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker image name
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$REPO_LOWER:latest
          echo "DOCKER_IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          file: ./Dockerfile.prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.PROD_COMPOSE_PATH }}

            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} docker compose -f docker-compose.prod.yml --env-file .env.prod pull backend

            DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --remove-orphans backend

            docker image prune -f